name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aebef45dc6f88bd7c1b364754697594dca2a4d8e993b766de6c450d5f2d2b0d6"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
