name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "167bab216cefaa7fb9ddac83f7130c8e0b1e3fd6629bd900f4a74f79d84fdb9f"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
