name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e2ba412cf58f135181841d41fca466234a250da3c9d9916ea3b69a5874ee34c"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
