name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c206a1fff99726648156f170c0998bc9e02d38af9dc735920fcd7d456d08cdf8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
