name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feb357e5f998cd9ec7de2f54428176a19d7c953c8f438f868d6fab41828f6613"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
