name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7381acfa0a551aafe0a368c9f7fab57cc297b3409b38dac1a43f0828f42a6ca0"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
