name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b88f001fd6025a0156b9846d4a62ffac015b09991768460641f959d5222457c1"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
