name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a66f85304601ef1eeb3e2d8ab2b6edaada4b372d548b55d7b0d549f60af929f"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
