name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58a6a265ad3d29a36d26d1acf04c79151659780c808b85f32d25cb75550f3639"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
