name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e77c7ca8685bcb3afe78a4d85989b44f7b8720bfd6bd298ef825c3082ac11e82"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
