name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8faefd83ac4ceb6b39becf94a36dae82672b4f93f3ba1ad37b385dd1236d094a"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
