name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80ac2867a1d69c130939ddb322a613163d2d13a93765648a32d8ef6cd9ce9ff5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
