name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ea53f1119bc715447cddc9303404c437f91efe9dce6b9e69ff4342951173736"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
