name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79fadaa5be08c694786b2d4719c7f85c9309b7e6dae06f7082c16708b055b3c6"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
