name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2c22d039718967be1e8b38663ea2abb414dd36d8c80c46e9a0af12e8f5b6777"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
