name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0262521796e6847da85c27b60c89890905813b6d248a51bd038c37a7d7091bb8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
