name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99d5f160f720e3293fdfd8bdf9e8d4b42d9e0166e6fc742dee766af0b478196d"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
