name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a61acd6f0a6525abfa0f643b2228aaaa0dfa58fb0835c995d345e6f497727b1"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
