name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d959238bcabaf23a4962d1ab64a4fa9f8b7e668b16dbacfb3bdfaaa3df96df8b"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
