name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cd2279b4fdc830d83d269c9d58b0575d25fac102a88d216fabf48d66a069e18"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
