name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e868728bd029420db075ec79d3a44fec6781b51f7955ab092b45b3c05d5aaf82"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
