name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e90153ab3ec3871b093eeef41391558fe1555df2ec31d79357ab424c7e0da5ac"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
