name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a35e2c18722a94a644db2423a4b4e31dd2d4470e0b6d95f9107734d9acefcb29"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
