name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57f7134095464f269cf2ff462bcaf9a120f9bfe413aae50286d5514dc4e88cdb"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
