name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ef7e03b53211bab9bb2a8ea9b2df803b6216c1f6abd2f5791e751abf22fa3a3"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
