name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78e02a520ed37bdc50a4b24f51b268c585a210bfbf3bca03bd97eb5a8bf3a3a9"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
