name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22c93266e52f9ed15e30c17e2d0b5af9a8e405fc806fca6f2419053c1c9bb433"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
