name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf57fbef596bbb3eaacdaa3ee92048878bcebde1a6778a075b827533eac00c1"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
