name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dab244768d49f4f631d927a2a3ee05da5e7dbb5f5f18e7ea302031daad5dc813"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
