name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c758c44e841fa8527ed9ef76ce9e42c82bc1167c436e06138f1b866d010574ba"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
