name = "Vaulters Paradise"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db60ef1cc9af7b4629fc9dc9433c4aca71f9f47fd4c199ed138a2e7c61d87a6e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
